# Generated by Django 4.2.14 on 2024-07-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingEvent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hotel_id', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('rpg_status', models.IntegerField()),
                ('room_id', models.IntegerField()),
                ('night_of_stay', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
        ),
    ]
